#! /usr/bin/env zsh

source "$HOME/.zsh_env"
source "$HOME/.zsh_alias"

# History

HISTFILE=~/.zsh_history
HISTSIZE=100000
SAVEHIST=100000

### BEGIN OPTIONS ###

setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FCNTL_LOCK # Can provide better performance when writing to the history file
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE # Command that start with a whitespace are not stored in the history
setopt HIST_LEX_WORDS # Treat quoted argument as single words. Can reduce performance on large history file
setopt HIST_NO_STORE # Do not store the history command in history
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt HIST_VERIFY # When using history expansion (!!), you have to press enter to execute the command
setopt SHARE_HISTORY

# Changing Directories

setopt CDABLE_VARS # Try to expand the expression as if it were preceded by a ~
setopt PUSHD_IGNORE_DUPS

# Completion

setopt ALWAYS_TO_END
setopt AUTO_NAME_DIRS # You can set directories paths in variable and access it with ~variable
setopt GLOB_COMPLETE # Add a menu selecter for globing

# Expansion and Globbing

setopt BAD_PATTERN # Warning if a pattern seems not correct
setopt EXTENDED_GLOB
setopt NOMATCH

# Input/Output

setopt PATH_DIRS # You can execute command from a subdirectory that is in the path
setopt PRINT_EXIT_VALUE
setopt RC_QUOTES # You can type 'it''s a nice day' instead of escaping the quote

# Job Control

setopt NOTIFY

# Prompting

setopt PROMPT_SUBST

# Zle

unsetopt BEEP

### END OPTIONS ###

bindkey -e
#bindkey '^a' beginning-of-line
#bindkey '^e' end-of-line

PROMPT=$'%F{blue}%~%f
%F{green}\U276F %f'

# Completion

zstyle ':completion:*' menu select
zstyle ':completion:*' completer _complete
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Za-z}' '+l:|=* r:|=*'

autoload -Uz compinit
compinit

autoload -Uz history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
# Linux
bindkey "^[OA" history-beginning-search-backward-end
bindkey "^[OB" history-beginning-search-forward-end

# MacOS
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end
